Repository PupDates-CrossPol/pupdates_frontend, pull requests merged in 2019-12, with the labels that each got.

#17 Add basic functionality for adding selected photo to state
  App.js
  package-lock.json
  package.json
Labels: enhancement, phase1

#19 Add functionality for taking photo to upload with camera
  App.js
  package-lock.json
  package.json
Labels: enhancement, phase1

#23 Nav bar create
  App.js
  components/AppNavigator/AppNavigator.js
  components/Home/Home.js
  components/LoginForm/LoginForm.js
  components/Menu/Menu.js
Labels: enhancement, frontend, phase2A

#25 Style nav bar across app with updated title image and placement of assets
  assets/PupDatesTitle.png
  assets/PupDatesTitleSpread.png
  components/DogPack/DogPack.js
  components/Home/Home.js
  components/Matches/Matches.js
  components/Menu/Menu.js
  components/UserProfile/UserProfile.js
Labels: Styling

#26 Sk look4matches
  components/Home/Home.js
  components/LoginForm/LoginForm.js
  package-lock.json
  package.json
Labels: enhancement

#27 Firebase setup
  .gitignore
  App.js
  GoogleService-Info.plist
  app.json
  components/LoginForm/LoginForm.js
  package-lock.json
  package.json
Labels: enhancement

#28 Mm menu buildout
  components/Menu/Menu.js
Labels: Styling, enhancement, phase2A

#29 Sk look4matches
  App.js
  components/Home/Home.js
  components/LoginForm/LoginForm.js
Labels: Styling, enhancement, question

#30 Mm match buildout
  components/Home/Home.js
  components/Match/Match.js
  components/Matches/Matches.js
Labels: Styling, enhancement, phase2A

#31 Image upload
  components/ImageUpload/ImageUpload.js
  components/LoginForm/LoginForm.js
Labels: enhancement

#33 Create Slider box for dog images on home component
  components/Home/Home.js
  package-lock.json
  package.json
Labels: enhancement, frontend, phase2B
