Repository PupDates-CrossPol/pupdates_frontend, pull requests merged in 2020-01, with the labels that each got.

#34 Login
  components/LoginForm/LoginForm.js
Labels: enhancement

#36 On user login fetch Dog Pack and associated dog photos
  actions/index.js
  components/LoginForm/LoginForm.js
  reducers/index.js
  reducers/pack.js
  reducers/packPhotos.js
  reducers/user.js
Labels: enhancement, frontend, phase2B

#38 User profile
  App.js
  apiCalls.js
  components/ImageUpload/ImageUpload.js
  components/LoginForm/LoginForm.js
  components/UserProfile/UserProfile.js
Labels: bug, enhancement

#40 User profile
  App.js
  actions/index.js
  apiCalls.js
  components/DogPack/DogPack.js
  components/ImageUpload/ImageUpload.js
  components/LoginForm/LoginForm.js
  components/UserProfile/UserProfile.js
  reducers/imageUpload.js
  reducers/index.js
  reducers/tempUserImage.js
Labels: enhancement

#43 User styling
  components/UserProfile/UserProfile.js
Labels: Styling

#53 User module
  components/ImageUpload/ImageUpload.js
  components/UserProfile/UserProfile.js
Labels: Styling, enhancement

#55 Image patching
  actions/index.js
  apiCalls.js
  components/AddDog/AddDog.js
  components/AddPhotosGrid/AddPhotosGrid.js
  components/ImageUpload/ImageUpload.js
  components/UserProfile/UserProfile.js
  reducers/index.js
  reducers/newDogImages.js
Labels: enhancement, help wanted

#63 Loading
  components/ImageUpload/ImageUpload.js
  images/loading_icon.gif
Labels: Styling, enhancement
